### ISSUE TITLE
Error: Invalid token (Format is Authorization: Bearer [token])

### ISSUE THREAD

**Issue by vextrogen** [NilsIrl/MozWire#28]
Just trying to set mozwire up but whenever I run the mozwire command it just gives me the error 

`Invalid token (Format is Authorization: Bearer [token])`.

Not sure why this is, been following the install instructions both for cargo and the pre-compiled binaries but nothing seems to work. Any help would be great!

Thanks

**Comment by vextrogen** [comment]
Actually, belay that. I literally just tried `sudo mozwire relay save` and it worked just fine. Sorry for the hassle.

**Comment by NilsIrl** [comment]
> Actually, belay that. I literally just tried `sudo mozwire relay save` and it worked just fine. Sorry for the hassle.

As opposed to? You shouldn't have to run mozwire as root (using `sudo`).

**Comment by vextrogen** [comment]
Odd, when I ran it without sudo it wouldn't work and gave me the error in the OP. Only running it with sudo allowed it to work, for me anyway.

**Comment by NilsIrl** [comment]
> Odd, when I ran it without sudo it wouldn't work and gave me the error in the OP. Only running it with sudo allowed it to work, for me anyway.

Did you specify the token in anyway? (using `--token` or `MOZ_TOKEN`)

**Comment by vextrogen** [comment]
I tried to set MOZ_TOKEN but it just gave me the same error. Same for --token

**Comment by NilsIrl** [comment]
> I tried to set MOZ_TOKEN but it just gave me the same error. Same for --token

The error shouldn't happen if you don't specify `MOZ_TOKEN` or `--token`. I suspect the error is because you specified an invalid token.
