### ISSUE TITLE
The login redirects to vpn.mozilla.org/vpn/client/login/deprecated

### ISSUE THREAD

**Issue by DEM0NAssissan7** [NilsIrl/MozWire#30]
When I used the "mozwire relay save" command, it redirected me to "vpn.mozilla.org/vpn/client/login/deprecated"
I literally cannot use the VPN service
I am using Ubuntu 20.10 completely updated
The browser was Firefox, also latest version

**Comment by NilsIrl** [comment]
Yes, I'm sorry, Mozilla changed their API, I'm working on a fix

**Comment by rlr** [comment]
@NilsIrl feel free to ping me if you have any questions. I can share some docs. ricky@mozilla.com

**Comment by NilsIrl** [comment]
I just release 0.6.0, which should now work, the difference is that now, once you log in in your browser, you'll have to copy-paste the URL you end up at (after some redirects) into MozWire.

@KeironO (in case they didn't subscribe to the issue)

**Comment by NilsIrl** [comment]
Just released v0.7.0 which brings back the old behaviour (where you don't have to copy-paste the code)
