### ISSUE TITLE
--port option is ignored when running `relay save`

### ISSUE THREAD

**Issue by davebenvenuti** [NilsIrl/MozWire#31]
mozwire 0.7.0 installed from cargo

Hardware: Raspberry Pi 3 Model B Rev 1.2  

OS: Raspbian Lite 10 (buster)

The `--port` option seems to be ignored as the generated authentication url looks like it contains a randomly generated port:

```
pi@raspberrypi:~ $ mozwire relay save --no-browser --port 12345
Please visit https://vpn.mozilla.org/api/v2/vpn/login/linux?code_challenge_method=S256&code_challenge=ZUJinAgnW9QfBm9YnGEkjjaXsrzaxlcHVdQayB46HdQ&port=34655.
```

**Comment by NilsIrl** [comment]
The `--port` option is for connecting to the VPN servers.

The port in the authentication URL is always random and there is no way to set it.
