### ISSUE TITLE
Failed to resolve interface "tun": No such device

### ISSUE THREAD

**Issue by ClonedOne** [NilsIrl/MozWire#32]
Hello, thank you for maintaining this tool it's really useful.

I have been using mozwire for a few months whithout any issue, but a couple of days ago, seeing that mozilla had released their linux client I tried installing that to check it out. Unfortunately it didn't work on my machine, and, much worse, now mozwire doesn't work anymore.

Now, whenever I use `wg-quick up` I end up with:
```
[#] resolvconf -a tun.us112-wireguard -m 0 -x
Failed to resolve interface "tun": No such device
[#] ip link delete dev us112-wireguard
```

I have purged the mozillavpn package, removed my box from the allowed devices and tried repeating the configuration steps from the beginning:
```
$ export MOZ_TOKEN=$(mozwire --print-token)
$ mozwire relay save
$ sudo wg-quick up ./us112-wireguard.conf
```
but I still get that error.

Do you know what may be causing it?

Edit: for completeness
```
$ uname -a
Linux  5.8.0-41-generic #46~20.04.1-Ubuntu SMP Mon Jan 18 17:52:23 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by NilsIrl** [comment]
I feel like it may be due to some kind of user-space wireguard implementation being left behind after installing the official mozilla VPN client. I am not sure however, what the exact issue is and am not sure I can really help much. This is a problem with the mozilla vpn client not mozwire. Although I'd love to help, you should probably ask them instead.

**Comment by ClonedOne** [comment]
I fear you are may be right, I was mostly hoping you may have seen this error before. I still can use wireguard to connect to a different vpn, so I guess the issue is somewhat related to mozilla's vpn in particular, but I am not sure where to start looking.

**Comment by NilsIrl** [comment]
If this problem was caused my installing the official VPN client you may want to contact mozilla. Here's the repo for that client where you might want to open an issue: https://github.com/mozilla-mobile/mozilla-vpn-client

**Comment by nikelborm** [comment]
Probably can be related to this issue:

https://bugs.launchpad.net/ubuntu/+source/wireguard/+bug/1992491

https://www.reddit.com/r/WireGuard/comments/yg13kl/problem_with_wireguardtun_module_after_updating/
