### ISSUE TITLE
Error when trying mozwire relay commands

### ISSUE THREAD

**Issue by alexander-jaferey** [NilsIrl/MozWire#33]
When attempting to run mozwire relay save, an error pops up:

`thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: reqwest::Error { kind: Request, url: "https://api.mullvad.net/public/relays/wireguard/v1/", source: hyper::Error(Connect, Custom { kind: Other, error: Os { code: 104, kind: ConnectionReset, message: "Connection reset by peer" } }) }', src/relay.rs:117:14`

here's the stack backtrace:

 

```stack backtrace:
   
   0: rust_begin_unwind
             at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/std/src/panicking.rs:475
   
   1: core::panicking::panic_fmt
             at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/core/src/panicking.rs:85
   
   2: core::option::expect_none_failed
             at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/core/src/option.rs:1221
   
   3: mozwire::relay::RelayList::new
  
   4: mozwire::main

**Comment by NilsIrl** [comment]
I was able to curl, the address without any issues, so I'm not sure what's the problem. It seems to be on your side. I don't think there's anything I can do apart from having a nicer error message. Let me know if this persists.

**Comment by alexander-jaferey** [comment]
Apologies, it was an issue with the public network I was attempting to run the commands on. Repeating the process while connected to my home network with a VPN fixed the issue
