### ISSUE TITLE
Invalid token (wrong format?) with --print-token

### ISSUE THREAD

**Issue by ralhei** [NilsIrl/MozWire#34]
I've compiled mozwire from the sources, everything went fine. Thanks a lot for this tool, btw.
I was able to obtain configurations with `mozwire relay save -o /etc/wireguard -n 0`, the directory is filled with conf files.

However if I want to obtain the token I get the following error:
```
$ export MOZ_TOKEN=$(mozwire --print-token)
Invalid token (Format is Authorization: Bearer [token])
```
Any idea what I'm doing wrong?

**Comment by NilsIrl** [comment]
Maybe `MOZ_TOKEN` was already set (to something invalid) when you ran that.

**Comment by ralhei** [comment]
Oops, you are fight, Interestingly it was set to an empty string ... after unsetting it indeed it works. Sorry for that, and thanks for your help.
