### ISSUE TITLE
Would it be possible to publish a new version?

### ISSUE THREAD

**Issue by tjni** [NilsIrl/MozWire#48]
The currently released version (0.7.0) no longer builds on Rust 1.64 because https://github.com/rust-lang/rust/pull/78802 breaks `socket2` versions older than 0.3.16. I noticed that the update to `clap` v3 on `trunk` also makes this necessary update. Would it be possible to schedule a release with this change, or schedule a patch release with an update to `socket2`?

In the meantime, I'll patch this in nixpkgs with those commits, so there isn't any urgency. Thank you!

**Comment by NilsIrl** [comment]
I just published a new version. Hopefully it fixes the issue. Let me know if there's anything I can do to help.

**Comment by tjni** [comment]
This is great, thank you so much!
