### ISSUE TITLE
Fail to build and install

### ISSUE THREAD

**Issue by AntHar** [NilsIrl/MozWire#49]
Hi,

I tried to build MozWire, but there is a failure regarding the type of strip in the section profile.release in the cargo.toml file

`
anton@antony-macbookpro MozWire % cargo install --git https://github.com/NilsIrl/MozWire.git --branch trunk
    Updating git repository `https://github.com/NilsIrl/MozWire.git`
error: failed to parse manifest at `/Users/anton/.cargo/git/checkouts/mozwire-1618045574137c89/e6bcc26/Cargo.toml`

Caused by:
  invalid type: unit variant, expected string only for key 'profile.release.strip'
`

**Comment by NilsIrl** [comment]
What version of cargo do you have?

**Comment by AntHar** [comment]
cargo 1.47.0 (f3c7e066a 2020-08-28)

**Comment by NilsIrl** [comment]
I'm not sure why this was happening as there doesn't seem to be a reason why `strip` cannot take a bool. But either way, it should be fixed now.

Thanks for reporting!
