### ISSUE TITLE
Unable to install 0.7.0 from AUR

### ISSUE THREAD

**Issue by JoshMock** [NilsIrl/MozWire#53]
Running Arch Linux on a ThinkPad and installing 0.7.0 via AUR helper `yay` fails:

```
error[E0512]: cannot transmute between types of different sizes, or dependently-sized types
   --> /home/joshmock/.cargo/registry/src/github.com-1ecc6299db9ec823/socket2-0.3.12/src/sockaddr.rs:176:9
    |
176 |         mem::transmute::<SocketAddrV4, sockaddr_in>(v4);
    |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |
    = note: source type: `SocketAddrV4` (48 bits)
    = note: target type: `sockaddr_in` (128 bits)

For more information about this error, try `rustc --explain E0512`.
error: could not compile `socket2` due to previous error
warning: build failed, waiting for other jobs to finish...
==> ERROR: A failure occurred in build().
    Aborting...
 -> error making: mozwire
```

I'm not sure if AUR packages use a preexisting compiler if available, but I'll note that I have the Rust compiler installed on my machine. So I ran `rustup update`, tried again, and got the same error.

I was able to get it to install via `cargo install mozwire` so perhaps the PKGBUILD scripts make some wrong assumptions about my environment?

**Comment by NilsIrl** [comment]
the AUR package is outdated. I plan on updating it but right now (for the next 10 days), I don't have the bandwidth to look at it.

**Comment by JoshMock** [comment]
No worries. Thanks for the update. This tool is so helpful. :black_heart:

**Comment by NilsIrl** [comment]
Sorry, it took me more time.

I updated the AUR package to the latest version, so it should be fixed now.

Thanks a lot Josh for the kind words
